# version: '3.8'

services:
  vue-app:
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "80:80"
    volumes:
      - ./front/src:/usr/share/nginx/html/src
      - ./front/public:/usr/share/nginx/html/public
    develop:
      watch:
        - action: sync+restart
          path: ./front/src
          target: /usr/share/nginx/html/src
        - action: rebuild
          path: ./front/package.json

  springboot-app:
    build: 
      context: ./impulsedata
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./impulsedata/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - FIREBASE_TYPE=service_account
      - FIREBASE_PROJECT_ID=impulsedata-alicantefutura
      - FIREBASE_PRIVATE_KEY_ID=003919b5ce1ec429adedb8bd6d40db31668be389
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6hLJaKb961SZB\nO8QVAQ2TQolco09a4ysxm4G2pBThQ0D0BoPuxs9XcSzsqu8aeZYML10xKVsLo5g5\nKrq1rEYRQBfYVMrQ+zBZxBLIjBEJN7rcZDL+Bdt2ThusjNYIHRhmMW8inZwaghuw\nsA/QU/pfOaoCTaXu3Du5KDKh1wQBny7sTSQOY0cwt7Fgt2dvXRVlgZdIob2ezziB\nVYD57JekDJrP3FUR8jZxfG+OTig2oVpHemW+bZSiRLKhieeOP/MwnInIPGWjykX/\nzb2HELefco7CcMt2sHd9yHrjJCEO34p6DrDSdrw2lXFzXb/GwFUhVO//3HixrCcb\nCe+HkBvrAgMBAAECggEAA/ukcV912tIlbHwxvj8VAqGHnGZSYf7646bN+M/9MChH\nAU8ITzeIovXkPzORQo/5H859H3kiHBgEvqfGb+27W0/ykmiRIjBTAn+45PZ0wK0j\nfORY4GrQmnClj6Q8R9UTOc9xb5xNApXnsHi6BbldXd413rG4yuaCEfylRCZ6y+wI\nazkkB0UoMYeXZNE8wwIzX9x5VNQ16AZCcOwCSqJC0dlT0snKIg3EyTGBetUFImSE\ncuTd9Xvfi/t1UBgSu6MULAnTFJUf+w/wAWVneMypbKIJpXbH05FOZIOVUVfqhhfl\n/+vQT4dzppM0S4lcubT85Rww7hRj/5pZErrE85LaXQKBgQDyJk3XnbkLOjtnM/3Z\nr8rIi/WaXhRmO0a4W/995ulXqITinzLrjrhQS8I4hIGl3XdYVxXPmw5C/zb6ooCb\n8aK3F82fCle09v+lxyGtd/hxSCJTQRAtrdvW30uHg07dtOQ3tL7M+U1EbxPD2g6q\n+lONd4QwQiLMW+MbpU+Yz+x5bQKBgQDFL86YXoWQny3r5RYwgRw+wOFJOx8t0olr\n5lQNYh33EVzK6yFsd8+96U9D31xiQulIMo2WiAKpvZOQYkrnmy9su5wiXgEffeMI\nm+yRKjv+w7Ow8Pk2RzSrQvCWpWRsmUmBcvCLhoZEpcitAYvDehIfiidyaCZ/bca5\n3L32zaArtwKBgEAe2HoB7+ADOXuojs23+RCFzzFjPC+d/qoO4maqYJuvqhCAa3Fo\nx3GrvfBNVi9fp5yi4smom2wuPJa9tSSWJaoqCW7VxEfNKADz6/0NSaJloYE+N1SB\nNzd8xXlK0fVvUwdVOzj3wvgeGbPA6CVqR/mr7jsBKEnJAyhs69jhJhM5AoGAcepl\neucYWG1tVRs6j3j3PVWmkOzj3VAE7d3ZbwXg88wHBH+EBqrMzBUOItLWBzpKlNgH\nrhATIcaQilgOl/CyHCniUIRoN649S8rwhwiUMmES3UTJZE8MoWgBn7Ya5xZDPdKO\nHrzvspbn8PK0sJBECg6BLXn3y6Q6q0NYR02Rm88CgYBjgSWKmP41TJCfkX0C0exF\ne0ht5qwDkKhHjuYw4u0hdVkwVpUnGNjCiCVofbLwB503rNk3y6Lh2h/Edh9J5R8Q\ndnjiSCswM/xPkjL0AwiP8Rmsv+dn5fdJS3d8piatp0lYFaGWLnSPOlHWAqO2ORzU\nlunCyNXdcr4RSsi2CjfxFQ==\n-----END PRIVATE KEY-----\n
    develop:
      watch:
        - action: sync+restart
          path: ./impulsedata/src
          target: /app/src
        - action: rebuild
          path: ./impulsedata/pom.xml
    depends_on:
      - vue-app
